### ISSUE TITLE
Altering from computed to normal field or visa versa is not supported

### ISSUE THREAD

**Issue by JaroslavKejnar** [cincuranet/FirebirdDbComparer#2]
Hello,

Do you plan to support the issue with computed field in source database and normal field in target database? (or normal field in the source and computed in the target)

FirebirdDbComparer.Exceptions.NotSupportedOnFirebirdException
  HResult=0x80131515
  Message=Altering from computed to normal field or visa versa is not supported 

Is there any option / configuration possible to leave out problematic 
Handle<IMetadataRelations>(x => x.AlterTablesAndToEmptyForAlteringOrDropping), "TABLES (alter, computed fields as shims for altering or dropping)" to get incomplete alter script?

Thank you for answer.

Best regards.
Jaroslav Kejnar
from company Elekt Labs s.r.o.

**Comment by cincuranet** [comment]
Hi,

> FirebirdDbComparer.Exceptions.NotSupportedOnFirebirdException
>   HResult=0x80131515
>   Message=Altering from computed to normal field or visa versa is not supported 

AFAIK there's no way to do this in Firebird. Only dropping and recreating the column. Which opens a can of worms with dependencies. 

Little bit of backround... Me and Danny took deliberately approach of doing only what the SQL commands offer (with very few small exceptions in Firebird 2.5) and not trying to do everything possible, rather provide sane scripts.

> Is there any option / configuration possible to leave out problematic 
> Handle<IMetadataRelations>(x => 
> x.AlterTablesAndToEmptyForAlteringOrDropping), "TABLES (alter, computed 
> fields as shims for altering or dropping)" to get incomplete alter 
> script?

That might actually good idea. For all these `NotSupportedOnFirebird` exceptions I can create fields in the context to signal either throwing or skipping (or something like that). If that would work for you, I would happily do that. Probably next week.

**Comment by dvdwouwe** [comment]
I agree here with Jiri.

Trying to do this is almost impossible. Did you try this with for example with IBExpert or another comparer?

Your 'work-around' sounds good, but we should at least give some remarks on top of our script-file which cases aren't covered.

**Comment by JaroslavKejnar** [comment]
Hello,

thank you for quick answer. 
I was thinking about drop and recreating, but you are right, there are a lot of problems with the dependencies.

Now, I am using the library without applying Compare function but use metadata objects and public function (e.g. HandleTriggers), so I don't need skipping `NotSupportedOnFirebird` exceptions right now.   

My solution to get alter script needs a custom SQL statements improving by internal company needs (e.g. insert statement into a table because of data replication, . . .) and your library serves me well.
Thank you very much.

Have a nice day.
